name: Python Wrapper Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'spannerlib/wrappers/spannerlib-python/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'spannerlib/wrappers/spannerlib-python/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: spannerlib/wrappers/spannerlib-python/spannerlib-python

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Nox
      run: pip install nox

    - name: Run Lint
      run: nox -s lint
